title: The Garikayi blogspot
description: > # this means to ignore newlines until "baseurl:"
  I blog about politics, education, and economics in Zimbabwe and Africa

permalink: /:categories/:title
url: http://valentinegarikayi.github.io/ # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: veegarikayi

# Author Settings
author: Vee Garikayi, (PhD) # add your name
author-img: pro-pic.jpg # add your photo
about-author: I am a researcher interested
              in African politics, economics
              and education. # add description
social-twitter: exploding_noema
social-facebook: # add your Facebook handle
social-github: valentinegarikayi # add your Github handle
social-linkedin: www.linkedin.com/in/francis-valentine-garikayi # add your Linkedin handle
social-email: fran.garikayi@gmail.com # add your Email address

# Disqus
discus-identifier: Schrodinger's-Cat # add your discus identifier

# Tracker
analytics: #Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
